group: "tutorial"
index: 0

advancements {
  root {
    type: "ROOT"
    children: ["create-island"]
    title: "Desolate Sky"
    description: "<secondary-color>Welcome to DesolateSky!"
    icon: "DIRT"
    frame: "TASK"
    x: 0
    y: 0
    background: "minecraft:block/dirt"
  }
  create-island {
    type: "CREATE_ISLAND"
    children: ["collect-thatch", "plant-cactus"]
    title: "Create Island!"
    description: "Create an island using /is create"
    icon: "DIRT"
    frame: "TASK"
    x: 2
    y: 0
  }
  collect-thatch {
    type: "COLLECT_ITEM"
    item: "desolatesky:thatch"
    children: ["craft-crafting-table"]
    title: "Collect Thatch"
    description: "Collect some thatch"
    icon: "BAMBOO"
    frame: "TASK"
    x: 3
    y: 1
  }
  plant-cactus {
    type: "PLACE_BLOCK"
    block: "minecraft:cactus"
    children: []
    title: "Plant Cactus"
    description: "Plant some cactus"
    icon: "CACTUS"
    frame: "TASK"
    x: 3
    y: -1
  }
  craft-crafting-table {
    type: "CRAFT"
    recipe: "minecraft:crafting_table"
    children: []
    title: "Crafting Table"
    description: "Craft a crafting table"
    icon: "CRAFTING_TABLE"
    frame: "TASK"
    x: 5
    y: 1
  }
}