"desolatesky:dry_grass_seeds": {
  block: "minecraft:beetroots"
  attributes: ["minecraft:mineable/hoe"]
  behaviors: {
    "desolatesky:dry_grass" {
      void-grass-chance: 0
    }
    "desolatesky:mining_speed": {
      ticks: 10
    }
    "desolatesky:supported_block": {
      support-direction: "DOWN"
      supporting-block-tags: ["#dirt", "#grass_blocks"]
      supporting-blocks: []
      supports-self: false
    }
  }
}
"minecraft:short_dry_grass": {
  attributes: ["minecraft:mineable/hoe"]
  behaviors: {
    "desolatesky:dry_grass" {
      void-grass-chance: 0
    }
    "desolatesky:mining_speed": {
      ticks: 10
    }
    "desolatesky:supported_block": {
      support-direction: "DOWN"
      supporting-block-tags: ["#dirt", "#grass_blocks"]
      supporting-blocks: []
      supports-self: false
    }
  }
}
"minecraft:tall_dry_grass": {
  attributes: ["minecraft:mineable/hoe"]
  behaviors: {
    "desolatesky:dry_grass" {
      void-grass-chance: 2
    }
    "desolatesky:mining_speed": {
      ticks: 20
    }
    "desolatesky:supported_block": {
      support-direction: "DOWN"
      supporting-block-tags: ["#dirt", "#grass_blocks"]
      supporting-blocks: []
      supports-self: false
    }
  }
}
"desolatesky:void_infused_bush": {
  block: "minecraft:closed_eyeblossom"
  attributes: ["minecraft:mineable/hoe"]
  behaviors: {
    "desolatesky:dry_grass" {
      void-grass-chance: 0
    }
    "desolatesky:mining_speed": {
      ticks: 20
    }
    "desolatesky:supported_block": {
      support-direction: "DOWN"
      supporting-block-tags: ["#dirt", "#grass_blocks"]
      supporting-blocks: []
      supports-self: false
    }
  }
}
"minecraft:cactus": {
  attributes: ["minecraft:mineable/axe"]
  behaviors: {
    "desolatesky:cactus" {
      growth-chance: 10
      flower-chance: 50
    }
    "desolatesky:mining_speed": {
      ticks: 40
    }
    "desolatesky:supported_block": {
      support-direction: "DOWN"
      supporting-block-tags: ["#dirt", "#grass_blocks"]
      supporting-blocks: []
      supports-self: true
    }
  }
}
"minecraft:cactus_flower": {
  attributes: ["minecraft:mineable/axe"]
  behaviors: {
    "desolatesky:cactus_flower" {
      water-chance: 100
      water-buckets-increment: 0.2
      max-water-buckets: 3
    }
    "desolatesky:mining_speed": {
      ticks: 100
    }
    "desolatesky:supported_block": {
      support-direction: "DOWN"
      supporting-block-tags: []
      supporting-blocks: ["minecraft:cactus"]
      supports-self: false
    }
  }
}
"minecraft:carrots": {
  attributes: ["minecraft:mineable/hoe"]
  behaviors: {
    "desolatesky:crop" {
      min-age: 0
      max-age: 7
      growth-chance: 50
      dropped-item: "minecraft:carrot"
      void-crop: "desolatesky:void_infused_carrot"
      min-drops: 1
      max-drops: 4
      remove-water-chance: 30
      void-crop-chance: 7
    }
    "desolatesky:mining_speed": {
      ticks: 40
    }
  }
}
"minecraft:potatoes": {
  attributes: ["minecraft:mineable/hoe"]
  behaviors: {
    "desolatesky:crop" {
      min-age: 0
      max-age: 7
      growth-chance: 45
      dropped-item: "minecraft:potato"
      void-crop: "desolatesky:void_infused_potato"
      min-drops: 1
      max-drops: 4
      remove-water-chance: 30
      void-crop-chance: 7
    }
    "desolatesky:mining_speed": {
      ticks: 40
    }
  }
}
