"desolatesky:void_core": {
  block: "minecraft:sculk_shrieker"
  behaviors: {
    "desolatesky:void_core": {
      generate-item-chance: 5
    }
  }
}
"minecraft:crafting_table": {
  behaviors: {
    "minecraft:crafting_table": {}
    "desolatesky:mining_speed": {
      ticks: 60;
    }
    "desolatesky:block_drop": {
      drops: {
        "minecraft:crafting_table": 1
      }
    }
  }
}
"minecraft:composter": {
  attributes: ["minecraft:mineable/axe"]
  behaviors: {
    "minecraft:composter": {}
    "desolatesky:mining_speed": {
      ticks: 60;
    }
  }
}
"minecraft:composter": {
  attributes: ["minecraft:mineable/axe"]
  behaviors: {
    "minecraft:composter": {}
    "desolatesky:mining_speed": {
      ticks: 60;
    }
  }
}
"desolatesky:small_barrel": {
  block: "minecraft:barrel"
  attributes: ["minecraft:mineable/axe"]
  behaviors: {
    "minecraft:barrel": {
      inventory_size: 9
      block_item: "desolatesky:small_barrel"
    }
    "desolatesky:mining_speed": {
      ticks: 60
    }
  }
}
