name: "tutorial"
index: 0

advancements {
  root {
    type: "ROOT"
    children: ["create-island"]
    title: "Desolate Sky!"
    description: "<secondary-color>Welcome to DesolateSky!"
    icon: "DIRT"
    frame: "TASK"
    x: 0
    y: 0
    background: "minecraft:block/dirt"
  }
  create-island {
    type: "CREATE_ISLAND"
    children: []
    title: "Create Island!"
    description: "Create an island using /is create"
    icon: "DIRT"
    frame: "TASK"
    x: 2
    y: 0
  }
  collect-thatch {
    type: "CREATE_ISLAND"
    children: []
    title: "Collect Thatch"
    description: "Collect some thatch"
    icon: "BAMBOO"
    frame: "TASK"
    x: 4
    y: 0
  }
}