group: "void"
index: 1

advancements {
  root {
    type: "ROOT"
    children: ["enter-void"]
    title: "The Void"
    description: ""
    icon: "SCULK"
    frame: "TASK"
    x: 0
    y: 0
    background: "minecraft:block/sculk"
  }
  enter-void {
    type: "ENTER_WORLD"
    world-type: VOID
    children: ["collect-void-infused-bush"]
    title: "Enter the Void"
    description: "Enter the void dimension"
    icon: "SCULK"
    frame: "TASK"
    x: 2
    y: 0
  }
  collect-void-infused-bush {
    type: "COLLECT_ITEM"
    item: "desolatesky:void_infused_bush"
    children: ["collect-carrot"]
    title: "Collect Void Infused Bush"
    description: "Hint: You'll need to grow dry bushes"
    icon: "CLOSED_EYEBLOSSOM"
    frame: "CHALLENGE"
    x: 3
    y: 1
  }
  collect-carrot {
    type: "COLLECT_ITEM"
    item: "minecraft:carrot"
    children: []
    title: "Collect Carrot"
    description: "Collect a carrot"
    icon: "CARROT"
    frame: "TASK"
    x: 5
    y: 1
  }
}