"desolatesky:thatch_planks": {
  block: "minecraft:bamboo_planks"
  attributes: ["minecraft:mineable/axe", "desolatesky:flammable"]
  behaviors: {
    "desolatesky:mining_speed": {
      ticks: 60
    }
    "desolatesky:wood_planks": {
      item: "desolatesky:thatch_planks"
    }
  }
}
"desolatesky:thatch_slab": {
  block: "minecraft:bamboo_slab"
  attributes: ["minecraft:mineable/axe", "desolatesky:flammable"]
  behaviors: {
    "desolatesky:thatch_slab": {
      ticks: 60
    }
  }
}
